Fixed issues with missing oc

diff --git a/.github/workflows/e2e_rhoai.yaml b/.github/workflows/e2e_rhoai.yaml
--- a/.github/workflows/e2e_rhoai.yaml
+++ b/.github/workflows/e2e_rhoai.yaml
@@ -255,7 +255,37 @@ jobs:
           echo "$HOME/bin" >> $GITHUB_PATH
 
       - name: Verify OpenShift installer
-        run: openshift-install version
+        run: |
+          if ! command -v openshift-install &> /dev/null
+          then
+            echo "❌ openshift-install not found. Installation failed."
+            exit 1
+          fi
+
+          echo "✅ openshift-install is installed."
+          openshift-install version
+
+      - name: Install OpenShift client (oc)
+        run: |
+          mkdir -p $HOME/bin
+          curl -L -o openshift-client-linux.tar.gz "https://access.cdn.redhat.com/content/origin/files/sha256/8b/8b94d4f6c78d070b764c1f83471cb3f1d68fa44279e9c8011c65d122196a6c08/openshift-client-linux-amd64-rhel9-4.19.10.tar.gz"
+          tar -xzf openshift-client-linux.tar.gz
+          rm openshift-client-linux.tar.gz
+          mv oc kubectl $HOME/bin/
+          chmod +x $HOME/bin/oc $HOME/bin/kubectl
+          echo "$HOME/bin" >> $GITHUB_PATH
+
+      - name: Verify OpenShift client installation
+        run: |
+          if ! command -v oc &> /dev/null
+          then
+            echo "❌ oc CLI not found. Installation failed."
+            exit 1
+          fi
+
+          echo "✅ oc CLI is installed."
+          oc version
+
 
       - name: list files 2
         run: |
